# training
epochs: 1000
lr: 0.01
weight_decay: 0
drop_prob: 0.7

# network
accum: split_stack
hidden_size: 
  - 500
  - 75
num_basis: 2
rgc_bn: True
rgc_relu: True
dense_bn: True
dense_relu: True
bidec_drop: False

# dataset
root: data/ml-100k
dataset_name: ml-100k

# comet-ml (optional)
workspace: 
project_name: 
api_key: 

# environment
gpu_id: -1 # -1 mean cpu